branches:
  only:
    - 1.0-develop
    - 1.1-develop
    - staging
sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - postfix
  chrome: stable
  hosts:
    - magento2.travis
services:
  - rabbitmq
  - elasticsearch
  - mysql
language: php
php:
  - '7.2'
  - '7.3'
env:
  global:
    - MAGENTO_HOST_NAME="magento2.travis"
    - MAGENTO_PROTOCOL="https"
    - MAGENTO_BACKEND="backend"
    - MAGENTO_ADMIN_USERNAME="admin"
    - MAGENTO_ADMIN_PASSWORD="123123q"
    - ADOBE_STOCK_LICENSED_IMAGE="175947395"
    - ADOBE_STOCK_UNLICENSED_IMAGE="24860368"
  matrix:
    - TEST_SUITE=unit
    - TEST_SUITE=phpstan
    - TEST_SUITE=static
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache
    # cache location of webdrivers for MFTF (chromedriver, geckdriver, etc)
    - $HOME/drivers
before_install:
  - bash -x dev/travis/before_install.sh
install:
  - mkdir -p magento2/app/code/Magento
  - mv Adobe* magento2/app/code/Magento/.
  - mv Media* magento2/app/code/Magento/.
  - pushd magento2
  - composer install
  - composer require astock/stock-api-libphp
  - popd
before_script:
  - bash -x dev/travis/before_script.sh
script:
  - bash -x dev/travis/script.sh
after_success:
  - if [ $TEST_SUITE == 'unit' ]; then travis_retry coveralls; fi
after_script:
  - bash -x dev/travis/after_script.sh
